### ISSUE TITLE
Incorporate JRuby bits into gem proper

### ISSUE THREAD

**Issue by headius** [tenderlove/psych#145]
For JRuby 1.7.5, I am attempting to offload several libraries as default gems, removing the code from our repository. Psych is on the hit list.

JRuby's psych has maintained compatibility up to now, so migrating our code into the Psych repo should not be a big deal. This would also allow Psych updates to be installable by JRuby users.

**Comment by headius** [comment]
Ok, we have a psych gem building using @mkristian's maven build. We are probably ready to start merging with the C gem, but we need to talk with @tenderlove about how best to combine the gems. We are using maven to build it rather than hoe, and we don't pass 100% of psych tests yet.

**Comment by tenderlove** [comment]
I can probably get the hoe integration working if you teach me how to build
with maven. Is there a rake task?

**Comment by mkristian** [comment]
actually https://github.com/mkristian/psych/tree/jruby already uses maven
and integrates with rake.

this branch works for building the java gem.

but I needed to add more files to Manifest.txt to get it working. and of
course you do not want to have all c-extension files inside the java gem
(or maybe that is ok)

here I stopped to get it working for MRI as well.

**Comment by headius** [comment]
It has been integrated but we're working out kinks. Calling this one closed.
