### ISSUE TITLE
Ruby 1.9.2-p320 Doesnt dump subclasses of Hashes

### ISSUE THREAD

**Issue by angelo0000** [tenderlove/psych#150]
I did a push to Heroku today and my app just started breaking all over the place.  I narrowed down the issue to the fact that when I call .to_yaml on a subclass of a Hash, I no longer get the class information serialized into the yaml.

I know there was an issue a long time ago with the same behavior.

I upgraded my heroku app to use ruby 1.9.3 and it seems to now serialize just fine. 

1.9.2-p320 Output:
```ruby
jakedempsey:jtmp angelo0000$ ruby -v
ruby 1.9.2p320 (2012-04-20 revision 35421) [x86_64-darwin11.4.2]
jakedempsey:jtmp angelo0000$ irb
irb(main):004:0> require 'psych'
=> true
irb(main):001:0> class Jake < Hash; end
=> nil
irb(main):005:0> Jake.new.to_yaml
=> "--- {}\n"
```

1.9.3 Output
```ruby
jakedempsey:d2m-ecommerce angelo0000$ ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin11.3.0]
jakedempsey:d2m-ecommerce angelo0000$ irb
require 'psych'
irb(main):001:0> require 'psych'
true
irb(main):002:0> class Jake < Hash; end
nil
irb(main):004:0> Jake.new.to_yaml
"--- !ruby/hash:Jake {}\n"
irb(main):005:0>
```

**Comment by hsbt** [comment]
Ruby 1.9 is already EOL. Please use Ruby 2.1 or 2.2.
