### ISSUE TITLE
Question: How to convert Psych's AST to JSON

### ISSUE THREAD

**Issue by mohsen1** [tenderlove/psych#206]
I asked [this](http://stackoverflow.com/questions/26185848/convert-psychs-ast-to-json) question in StackOverflow with no luck. I want to get a JSON tree from AST. How can I do this?

```ruby
    gem 'psych'
    require 'psych'
    require 'json'
    
    ast = Psych.parse_stream("me: 1");
    
    p ast
```
`ast.to_json` doesn't give me the JSON tree.

**Comment by tenderlove** [comment]
You'll need to walk the tree by hand and do your own conversions.  Each node should respond to `children`, so you should be able to walk that tree and construct anything you want.

Hope that helps!
