### ISSUE TITLE
Psych breaks on \u0084 character

### ISSUE THREAD

**Issue by d4rky-pl** [tenderlove/psych#207]
```
2.1.1 :003 > YAML.load("a: '\u0084'")
Psych::SyntaxError: (<unknown>): control characters are not allowed at line 1 column 1
	from /Users/d4rky/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/psych.rb:370:in `parse'
	from /Users/d4rky/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
	from /Users/d4rky/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/psych.rb:318:in `parse'
	from /Users/d4rky/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/psych.rb:245:in `load'
	from (irb):3
	from /Users/d4rky/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'
```

**Comment by tenderlove** [comment]
I think that might be a problem with your ruby literals.  How about this instead:

```
Psych.load('a: \'\u0084\'')
```

**Comment by d4rky-pl** [comment]
The problem occured while consuming an external API. The code you've just shown me escapes the sequence (`\\u0084` instead of `\u0084`) which is not exactly a solution to the problem :)

**Comment by d4rky-pl** [comment]
Excerpt from YAML 1.2 spec:

> To ensure readability, YAML streams use only the printable subset of the Unicode character set. The allowed character range explicitly excludes the C0 control block #x0-#x1F (except for TAB #x9, LF #xA, and CR #xD which are allowed), DEL #x7F, the C1 control block #x80-#x9F (except for NEL #x85 which is allowed), the surrogate block #xD800-#xDFFF, #xFFFE, and #xFFFF.

So it seems that Psych is acting properly according to spec and the problem was with the malformed input. Sorry for wasting your time!

**Comment by tenderlove** [comment]
@d4rky-pl no problem at all.  I wasn't sure if it was a Ruby escaping issue, or if it just wasn't supported per spec.  Thanks for looking it up for me, I really appreciate it!
