### ISSUE TITLE
Serialization of cross-referrenced objects with psych

### ISSUE THREAD

**Issue by ineverov** [tenderlove/psych#208]
I'm trying to run next code that serialize object B that has instance variable of A initialized with this B (cross referenced). After deserialization I'm getting 2 B objects instead of 1

https://gist.github.com/ineverov/3ce3ea21d970996b673e

During investigation of source code of psych I found that we don't register objects that use encode_with methods
Here: https://github.com/ruby/ruby/blob/trunk/ext/psych/lib/psych/visitors/yaml_tree.rb#L530

**Comment by tenderlove** [comment]
Hi, this was fixed in 43fa4aa38492c80080efa61aa4b7bee422792bc7 and released in v2.0.13
