### ISSUE TITLE
Fail load file with a value with char '\' (that is not escape)

### ISSUE THREAD

**Issue by narcisobenigno** [tenderlove/psych#209]
It works in syck
``` yaml
# given a file in /Users/mymachine/test.yml with content:
t: "\027\200"
```
```ruby
irb(main):003:0> YAML::ENGINE.yamler = 'syck'
=> "syck"
irb(main):004:0> y = YAML.load_file("#{ENV['HOME']}/test.yml")
=> {"t"=>"\u000027\\200"}
```

But it does not work in psych:
```ruby
irb(main):005:0> YAML::ENGINE.yamler = 'psych'                                                                                         
=> "psych"
irb(main):006:0> y = YAML.load_file("#{ENV['HOME']}/test.yml")
Psych::SyntaxError: (/Users/mymachine/test.yml): found unknown escape character while parsing a quoted scalar at line 1 column 4
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/psych.rb:203:in `parse'
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/psych.rb:151:in `parse'
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/psych.rb:127:in `load'
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/psych.rb:297:in `block in load_file'
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/psych.rb:297:in `open'
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/psych.rb:297:in `load_file'
        from (irb):6
        from /Users/mymachine/.rubies/ruby-1.9.3-p545/bin/irb:12:in `<main>'
```

**Comment by tenderlove** [comment]
I'm not sure what to tell you.  It's not valid YAML, so libyaml won't accept it.  You can install syck as a gem, then migrate the old yaml format to new yaml by doing something like:

```ruby
value = Syck.load_file("the file")
File.open("the file", 'w') { |f| f.write Psych.dump(value) }
```

**Comment by hardik-plume** [comment]
@tenderlove i have below entry in yaml and it is a valid yaml

`invalid_email_address: "L\'adresse e-mail n\'est pas valide"`

and i get below error:

`Hardiks-MacBook-Pro-3:~ hardik$ irb
2.6.1 :001 > require 'YAML'
 => true 
2.6.1 :002 > YAML.load_file File.open("/Users/Hardik/projects/mobile-automation/spec/fixtures/translations/fr.yml")
Traceback (most recent call last):
       11: from /Users/hardik/.rvm/rubies/ruby-2.6.1/bin/irb:23:in `<main>'
       10: from /Users/hardik/.rvm/rubies/ruby-2.6.1/bin/irb:23:in `load'
        9: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        8: from (irb):2
        7: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/psych.rb:577:in `load_file'
        6: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/psych.rb:577:in `open'
        5: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
        4: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/psych.rb:277:in `load'
        3: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/psych.rb:390:in `parse'
        2: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
        1: from /Users/hardik/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/psych.rb:456:in `parse'
Psych::SyntaxError ((#<File:0x00007f927c8bc5c0>): found unknown escape character while parsing a quoted scalar at line 3 column 26)`
