### ISSUE TITLE
'nil' does not roud-trip through load/dump

### ISSUE THREAD

**Issue by silarsis** [tenderlove/psych#227]
YAML.load recognises '~' as a nil value - but when dumping back out, it converts that nil to an empty string, rather than outputting the original ~.

Is there any way to get dump to generate ~ characters for nil?

**Comment by tenderlove** [comment]
No.  I haven't made one.  I guess I could, but I'm not sure why.

**Comment by silarsis** [comment]
My use case is an app that reads a template yaml, updates and writes back out - right now, all my nils (used to indicate that values are expected but haven't yet been set) are being converted to empty strings. I can cope with that elsewhere, but it means `.nil?` checks extend out to `.nil? || .empty?`

**Comment by tenderlove** [comment]
Can you give me some demo code?  How is it getting converted to empty strings?

```
irb(main):006:0> x = '~'
=> "~"
irb(main):007:0> Psych.load x
=> nil
irb(main):008:0> Psych.load Psych.dump Psych.load x
=> nil
irb(main):009:0> Psych.dump Psych.load x
=> "--- \n...\n"
irb(main):010:0> Psych.load Psych.dump Psych.load x
=> nil
```

**Comment by silarsis** [comment]
I haven't been able to replicate this outside of the codebase I was working on, and I'm not working on that codebase any more. So I suspect it was related to my code, not the library code. Closing, thanks for the assistance.

**Comment by ahoglund** [comment]
I have a similar issue to this, where I would like to be able to have `Psych.dump` use the [canonical form](url) of a null value when emitting.  As of right now, it defaults to an empty value even if the source value loaded in was `null`.

current behavior:
```irb(main):015:0> x = "null"                 
=> "null"                                   
irb(main):016:0> Psych.load x               
=> nil                                      
irb(main):017:0> Psych.dump Psych.load x    
=> "--- \n"
```

desired behavior:

```
irb(main):015:0> x = "null"                 
=> "null"                                   
irb(main):016:0> Psych.load x               
=> nil                                      
irb(main):017:0> Psych.dump Psych.load x    
=> "--- null\n"
```

Is there a way I can accomplish this currently?
