### ISSUE TITLE
Collon in anchor name returns Psych::SyntaxError: (<unknown>): 

### ISSUE THREAD

**Issue by vmoravec** [tenderlove/psych#231]
The exact error message is:
`Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 27 column 18`

The document at http://www.yaml.org/spec/1.2/spec.html, chapter `6.9.2. Node Anchors` says that

`Anchor names must not contain the “[”, “]”, “{”, “}” and “,” characters. These characters would cause ambiguity with flow collection structures.` A collon should work fine here.

Yaml example:
```yaml
features: &feature:admin
  admin:
    - core
```

Thanks for looking into this.

**Comment by tenderlove** [comment]
[libyaml implements the 1.1 spec](http://pyyaml.org/wiki/LibYAML).  When libyaml supports the 1.2 spec, this will work.
