### ISSUE TITLE
String quoting differs between 2.0.0 and 2.0.8

### ISSUE THREAD

**Issue by segiddins** [tenderlove/psych#232]
In v2.0.0, which I believe shipped by default with Ruby 2.0, `h = { k: './Hello' }` would serialize to `---\n:k: ./Hello\n`, whereas in 2.0.8, which I have on my 2.2.1 install, it serializes to  `---\n:k: "./Hello"\n` -- note the added quotes in the later version. This causes unwanted diffs when the same file is serialized by different ruby versions.

**Comment by segiddins** [comment]
@tenderlove this is a breaking change for CocoaPods' users, it would be nice to know if there's anything we can do about it

**Comment by tenderlove** [comment]
Sorry, how is this a "breaking change"?

**Comment by segiddins** [comment]
Because the generated YAML strings are unequal

**Comment by tenderlove** [comment]
Psych never makes a guarantee that the output will always be the same.  It guarantees that any object you serialize will deserialize the same way, so I don't consider this to be a "breaking change".  I am open to a patch that would make strings serialize how you want, but I reiterate: psych makes **no** guarantees about what the output YAML will look like, only that an object can serialize and deserialize successfully.
