### ISSUE TITLE
undefined class/module reading-back class serialized from module, ruby 2.1.5, Rails 4.1.13

### ISSUE THREAD

**Issue by wbreeze** [tenderlove/psych#252]
A colleague is a fan of yours, so I'll take the time to write this up; however, I don't have time to properly give you a test to reproduce it, or better, give you a patch.  For that, I apologize.  Pardon me as well if I've totally missed something, screwed up the usage, and made my own problem.  Also, this with ruby 2.1.5, Rails 4.1.13.  If this is already repaired in a later version, I haven't taken the time to upgrade in hopes of picking-up a repair.  Again, my apologies.

This code https://github.com/wbreeze/iaccdb/blob/master/lib/acro/contest_extractor.rb defines class `ACRO::ContestExtractor`  that uses `YAML.dump` to write the content of a module `ACRO::PilotFlightData`.
```
      pfd = PilotFlightData.new
      pfd.process_pilot_flight(pilot_scraper)
      File.open(f + '.yml', "w") {|out| YAML.dump(pfd, out)}
```

This code https://github.com/wbreeze/iaccdb/blob/master/lib/acro/contest_flights.rb defines a class `ACRO::ContestFlights` that uses `YAML.load_file`
```
        pilot_flight_data = YAML.load_file(f)
```
to restore the `ACRO::PilotFlightData` instance.  It emits the following error.

```
undefined class/module ACRO::PilotFlightData
/Users/dclo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/class_loader.rb:53:in `path2class'
/Users/dclo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/class_loader.rb:53:in `resolve'
/Users/dclo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/class_loader.rb:45:in `find'
/Users/dclo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/class_loader.rb:27:in `load'
/Users/dclo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:360:in `resolve_class'
/Users/dclo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:203:in `visit_Psych_Nodes_Mapping'
```

The workaround is to load the class before attempting to read the YAML file,
```
pfl = PilotFlightData.new
```
evidenced in this commit: https://github.com/wbreeze/iaccdb/commit/f3b2f471779ed67ffa6f3f98d78728188ec7c4ad

Is it something Rails does for me that YAML/psych cannot?  Perhaps that's the rub.  I can say that this code worked last year.  I'd have to research versions in use then.  Haven't taken the time to do that either.  A workaround is so demotivating to proper fixing!  And I have a job to do...  Thank you!

**Comment by elfassy** [comment]
same issue with Rails 4.2.6, ruby 2.1.2

```
ArgumentError: undefined class/module Advance::
```
Where `Advance` is the module name for a class which exists in the app.

**Comment by alexggordon** [comment]
All:

Instead of doing ugly things like ```pfl = PilotFlightData.new```, you can monkey patch a fix (which is below). 

This fix rescues the undefined class/module error, parses the module out of the error, and then tries to get the class name from the module, which if successful will add the class to the cache of known classes, therefore allowing it to be parsed. 

Just stick the below patch in an initializer and you're good to go. 

If this patch is something along the lines of what is acceptable to the Psych maintainers I'm happy to pull request it. 

    require 'yaml'

    # this fixes https://github.com/tenderlove/psych/issues/252
    # By rescuing the undefined class/module and adding it to to the stored constants
    module Psych
      def self.load(yaml, filename = nil, max_retries=100)
        retries = 0
        begin
          result = Psych.parse(yaml, filename)
          result ? result.to_ruby : result
        rescue ArgumentError => e
          retries += 1
          if e.message.include?('undefined class/module') && retries < max_retries
            name = e.message.sub 'undefined class/module ', ''
            parts = name.split '::'
            if parts.length == 1
              klass = parts.only
              mod = Module
            else
              klass = parts[-1]
              mod = parts[0..-2].join('::').constantize
            end

            mod.const_get klass
            retry
          end
          raise e
        end
      end
    end

**Comment by jrafanie** [comment]
Another option: hook psych to try Rails autoload on class lookup:

https://github.com/ManageIQ/manageiq/blob/bda98099e7decdf2d7287435549e84877c724b22/config/initializers/yaml_autoloader.rb#L6

**Comment by alexggordon** [comment]
@jrafanie that was actually my first thought. However, I found that to be a HUGE speed detriment to loading serialized data in this situation. I never pulled actual numbers, but in just using rails I noticed a pretty significant speed increase. If you're curious, that monkey patch (from [SO](http://stackoverflow.com/questions/4705867/rails-doesnt-load-classes-on-deserializing-yaml-marshal-objects))


    module Psych::Visitors
      ToRuby.class_eval do
        alias :resolve_class_without_autoload :resolve_class
        def resolve_class klassname
          begin
            require_dependency klassname.underscore 
          rescue NameError, LoadError
          end
          resolve_class_without_autoload klassname
        end
      end
    end

**Comment by jrafanie** [comment]
> However, I found that to be a HUGE speed detriment to loading serialized data

@alexggordon what part is slow?  If the class is already loaded, it should be close to a no-op, hopefully.  We actually did something similar to your snippet before and didn't notice a measurable performance with the current way, using safe_constantize with Module prepend.

**Comment by wbreeze** [comment]
Is that the problem?  That my code relies on Rails autoload?  No reason to tie Psych into Rails.  No good coupling the two or making a dependency.  My work-around is still working.

This marshaling YAML into Ruby objects is of course clever.  There are similar things for XML and Java (as if we care).  Yet maybe it's smarter to parse "manually."  Ramble on...

**Comment by jrafanie** [comment]
> Is that the problem? That my code relies on Rails autoload? No reason to tie Psych into Rails. No good coupling the two or making a dependency. My work-around is still working.

@wbreeze AFAIK, your workaround is relying on rails autoload.  I assume lib is autoloaded so Rails may already be loaded.  I agree, don't tie yourself to Rails if you don't have to, but if rails is already loaded, [this workaround will handle any class that Rails can figure out how to autoload](https://github.com/ManageIQ/manageiq/blob/bda98099e7decdf2d7287435549e84877c724b22/config/initializers/yaml_autoloader.rb#L6)... Note, it requires modern rubies with module prepend.

@alexggordon's patch will work with straight ruby, although I believe Rails autoload is a bit more magical in finding the missing constant.

Either way, I don't think straight psych can solve this problem for you.  It has no idea what classes you want to YAML.load.

**Comment by wbreeze** [comment]
I agree.  I think this was an expectation due to taking Rails autoload as given.  Nothing to do with Psych.

Others might come to the table with that expectation as well, and this thread might help them.  But they'll have to find it in the closed issues.

**Comment by Ceasar** [comment]
For anyone encountering this issue in the future: a good explanation for why this error happens can be found [on StackOverflow](https://stackoverflow.com/questions/13750342/yamlload-raises-undefined-class-module-error/13750743#13750743).

> When you use `YAML.dump` to serialize an object in Ruby, the class name is use as part of the Yaml tag so that the correct class can be used when loading the object. For example:
> 
> 
> 
>     require 'yaml'
>     
>     class Foo; end
>     
>     puts YAML.dump Foo.new
> 
> produces
> 
> 
> 
>     --- !ruby/object:Foo {}
> 
> When you use `YAML.load` on that string, Psych knows what class to instantiate for the deserialized object.
> 
> If you try to call `YAML.load` on a Yaml string that specifies a class that hasn’t been defined, then you will get the error:
> 
> 
> 
>     require 'yaml'
>     
>     # No Bar class has been defined
>     YAML.load '--- !ruby/object:Bar {}'
> 
> produces:
> 
>     /Users/matt/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:312:in `path2class': undefined class/module Bar (ArgumentError)
>     	from /Users/matt/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:312:in `resolve_class'
>     ...
> 
> This is because Psych needs to create an instance of class `Bar`, but doesn’t have the definition of the class available. This explains why adding `require 'whatever'` before loading the Yaml works – now Ruby has the definition of the class loaded and so can create an instance of it (note that there is no definitive link between class name and file name in Ruby, it’s just convention).
> 
> The solution therefore is to make sure that when you’re loading any Ruby objects from Yaml you have already required any files that may contain definitions of any classes potentially in that Yaml.
