### ISSUE TITLE
Excessive quoting with line_width: -1

### ISSUE THREAD

**Issue by glebm** [tenderlove/psych#254]
Recent versions of YAML quote excessively with line_width -1.

For example:

```console
> puts Psych.dump({'b' => 'c'}, {line_width: -1})
---
"b": >-
  c
```

If you are bisecting this, the bug is not in 2.0.8 but is in 2.0.13, so it's somewhere in between. A cursory look show this as a likely suspect: https://github.com/tenderlove/psych/commit/2edf642b82ae88ed93ec5f6ed7ae699771c04fc6.

**Comment by tenderlove** [comment]
Yep, this seems like a bug.  What would you expect `-1` to do?  My initial reaction is that it should raise an ArgumentError, since a negative line width seems like a result of a bug.  How are you encountering this?

**Comment by glebm** [comment]
Not as a result of a bug: I have been [recommending](https://github.com/glebm/i18n-tasks/blob/7e6418e97458d3fb3d196aa3661fd5755109918f/templates/config/i18n-tasks.yml#L39) the users of my gem to use `-1` to remove max line width for years. ^^'

Throwing an `ArgumentError` for `-1` could be OK if we document that `0` is the one true value to use to disable max width. It seems unlikely that this value is set dynamically in the user's code though, so perhaps we could just make values `<= 0` work again?

If we throw an `ArgumentError`, the major version should probably be bumped.

**Comment by glebm** [comment]
Turns out `line_width: 0` is broken as well.

**Comment by glebm** [comment]
Actually, `-1` is documented as unlimited in the C API here:
https://github.com/tenderlove/psych/blob/master/ext/psych/yaml/yaml.h#L1864

**Comment by glebm** [comment]
@tenderlove I've given it a go in #255.
However, I discovered another issue: if line_width is not passed, `best_width` in [yaml.h:1609](https://github.com/tenderlove/psych/blob/c1decb1fef5c77d84a93d5ac19a4961da914dd5c/ext/psych/yaml/yaml.h#L1609) is actually garbage (uninitialised memory). Because it's garbage, sometimes it's greater or equal than zero, in which case it defaults to 80 [here](https://github.com/tenderlove/psych/blob/c1decb1fef5c77d84a93d5ac19a4961da914dd5c/ext/psych/yaml/emitter.c#L514), but at other times it's negative and it defaults to MAX_INT [here](https://github.com/tenderlove/psych/blob/c1decb1fef5c77d84a93d5ac19a4961da914dd5c/ext/psych/yaml/emitter.c#L518).
