### ISSUE TITLE
ArgumentError: "invalid value for Float()" when loading multiline string that looks like float

### ISSUE THREAD

**Issue by jhund** [tenderlove/psych#267]
Thank you very much for all your work on the psych Gem!

When I load a multiline string where at least one line looks like a float, I get an `ArgumentError: "invalid value for Float()"`. Psych falsely interprets the multiline string as a float:

~~~ ruby 
yaml = %(---
foo:
- ! \"1.\\n2.\")

Psych.load(yaml)
~~~

This code snippet generates the following error:

~~~
ArgumentError: invalid value for Float(): "1\n2"
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/scalar_scanner.rb:102:in `Float'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/scalar_scanner.rb:102:in `tokenize'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:116:in `deserialize'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:122:in `visit_Psych_Nodes_Scalar'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:295:in `block in register_empty'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:295:in `each'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:295:in `register_empty'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:140:in `visit_Psych_Nodes_Sequence'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:302:in `block in revive_hash'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:300:in `each'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:300:in `each_slice'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:300:in `revive_hash'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:161:in `visit_Psych_Nodes_Mapping'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:276:in `visit_Psych_Nodes_Document'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/visitors/to_ruby.rb:31:in `accept'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/nodes/node.rb:37:in `to_ruby'
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych.rb:246:in `load'
  from (irb):91
  from /Users/redacted/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'2.1.5 :092 >
~~~

I think this has to do with the regex that parses for floats. It uses `^` and `$` to test for floats. Shouldn't the regex use `\A` and `\z` (string start and end vs. line start and end) to avoid this kind of issue?

The offending regex is located in [psych/lib/psych/scalar_scanner.rb](https://github.com/tenderlove/psych/blob/8d3a63e7e8480d987a916d1ca46ece0d5e071c9d/lib/psych/scalar_scanner.rb#L11)

Let me know if you want me to submit a pull request that replaces the `^` with `\A` and `$` with `\z`. I would also update the test for ScalarScanner with test cases for this scenario.

**Comment by tenderlove** [comment]
@jhund yes, please send a PR. I'd be happy to merge it!

**Comment by jhund** [comment]
I just had a look at `scalar_scanner.rb` and saw that there are a lot of regexes which use `^` and `$` and should probably be converted to `\A` and `\z`. Would you prefer a narrowly focussed PR, just for my issue, or should I clean them all up (as appropriate)?

**Comment by tenderlove** [comment]
@jhund send one PR just for this narrow case, then follow up with a second PR to address the other regexps.  Some of the regexps in there are for performance reasons, so I'd like to make sure that these two commits are kept separate.  Thank you very much!

**Comment by jhund** [comment]
@tenderlove turns out that this issue doesn't exist any more in the current version of Psych (2.0.17). I can reproduce it with the version that is bundled with Ruby 2.1.5 (Psych 2.0.5), however I can't reproduce it with Psych 2.0.17.

So I can work around this by installing the current gem version of Psych in my app. I didn't investigate what fixed it. At first glance the regex in ScalarScanner seems unchanged.

As far as I'm concerned, the issue is resolved.
