### ISSUE TITLE
scientific notation numbers are loaded as strings instead of floats

### ISSUE THREAD

**Issue by Voker57** [tenderlove/psych#280]
Example: > Psych.load "9e5"
=> "9e5"
Should be: 
=> 900000.0

**Comment by tenderlove** [comment]
According to [this](http://yaml.org/type/float.html), a decimal point is required, and a sign after the "e" is required.  So I guess that should be "9.0e+5".  Am I missing something?

**Comment by Voker57** [comment]
Oh, I was under impression that psych parses yaml 1.2. For 1.1, indeed, it's correct behavior.

**Comment by perceptec** [comment]
FWIW, (the underlying) libyaml is based on [1.1](http://pyyaml.org/wiki/LibYAML), with 1.2 support [requested](https://bitbucket.org/xi/libyaml/issues/9/yaml-12-support).
